-- Backend-only access. The app database role must own these tables.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE users FROM anon, authenticated;
ALTER TABLE circles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE circles FROM anon, authenticated;
ALTER TABLE circle_memberships ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE circle_memberships FROM anon, authenticated;
ALTER TABLE persons ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE persons FROM anon, authenticated;
ALTER TABLE relationships ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE relationships FROM anon, authenticated;
ALTER TABLE change_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE change_requests FROM anon, authenticated;
ALTER TABLE context_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE context_events FROM anon, authenticated;
ALTER TABLE person_context_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE person_context_links FROM anon, authenticated;
ALTER TABLE media_assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE media_assets FROM anon, authenticated;
ALTER TABLE person_places ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE person_places FROM anon, authenticated;
ALTER TABLE discussion_threads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE discussion_threads FROM anon, authenticated;
ALTER TABLE discussion_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE discussion_messages FROM anon, authenticated;
ALTER TABLE entity_revisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE entity_revisions FROM anon, authenticated;
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE auth_sessions FROM anon, authenticated;
ALTER TABLE circle_access_tickets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE circle_access_tickets FROM anon, authenticated;
ALTER TABLE circle_invitations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE circle_invitations FROM anon, authenticated;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE audit_logs FROM anon, authenticated;
